repos:
  #################################################################################
  # isort alphabetizes your python imports and groups them                        #
  # We skip the anything else that isn't part of the repo (excluded by gitignore) #
  #################################################################################
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          - -l=95
          - --py=39
          - --filter-files
          - --skip-gitignore

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - --line-length=95

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [ python ]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]

  # trailing-whitespace  is a simple hook which trims trailing whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
        args: [ "--unsafe" ]
