version: '3.9'
services:
  local_postgres:
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/usr/share/postgres/data
    env_file:
      - ./db/.env.local.db
    # instead, we could have created a `environment` section, with
    # with the env vars in .env.local.db file.
  local_grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - 3000:3000
    user: root
    volumes:
      - grafana_data:/usr/share/grafana/data
    env_file:
      - ./grafana/.env.local.grafana
volumes:
  postgres_data:
  grafana_data:
